@extends('layouts.app')
@section('title', 'Ledger & reports')
@section('content')
<div class="page-heading"><div><p class="eyebrow">EVERY CREDIT, ACCOUNTED FOR</p><h1>A clear view of campus transport.</h1><p>Online booking revenue only. Walk-in cash payments are outside this system.</p></div></div>
<form method="get" class="filter-bar"><label>From<input type="date" name="from" value="{{ $from }}" required></label><label>To<input type="date" name="to" value="{{ $to }}" required></label><button class="btn btn-primary btn-small" type="submit">Apply dates</button></form>
<div class="stats-grid">@foreach([['Online booking revenue',$totals['bookings']],['Reversed fares',$totals['refunds']],['Net online revenue',$totals['bookings']-$totals['refunds']],['Admin-issued credit',$totals['credits']]] as [$label,$value])<div class="stat"><span>{{ $label }}</span><strong class="small-value">{{ \App\Support\Money::format((int)$value) }}</strong></div>@endforeach</div>
<section class="panel section-gap"><h2>Driver earnings in this period</h2><div class="earnings-grid">@forelse($drivers as $driver)<div class="price-row"><span>{{ $driver->name }}</span><strong>{{ \App\Support\Money::format((int)$driver->net_kobo) }}</strong></div>@empty<p class="muted">No online booking earnings in this date range.</p>@endforelse</div></section>
<section class="panel section-gap"><h2>Transfer ledger</h2><p>Each fare transfer links one student debit to one driver credit. Refunds retain the original transfer reference.</p><div class="table-scroll"><table><thead><tr><th>Reference / kind</th><th>Booking / run</th><th>Amount</th><th>Actor / recipient</th><th>Reason</th><th>Time</th></tr></thead><tbody>@forelse($transfers as $transfer)<tr><td><code>TX-{{ str_pad($transfer->id,6,'0',STR_PAD_LEFT) }}</code><small>{{ ucfirst($transfer->kind) }}</small>@if($transfer->original_transfer_id)<small>Reverses TX-{{ str_pad($transfer->original_transfer_id,6,'0',STR_PAD_LEFT) }}</small>@endif</td><td>{{ $transfer->booking?->booking_code ?? '—' }}@if($transfer->booking)<small>Run #{{ $transfer->booking->run_id }} · {{ $transfer->booking->run->bus->identifier }}</small>@endif</td><td class="nowrap">{{ \App\Support\Money::format($transfer->amount_kobo) }}</td><td>{{ $transfer->actor->name }}<small>To {{ $transfer->recipient?->name }}</small></td><td>{{ $transfer->reason }}</td><td class="nowrap">{{ $transfer->created_at->format('d M Y') }}<small>{{ $transfer->created_at->format('g:i A') }} WAT</small></td></tr>@empty<tr><td colspan="6" class="table-empty">No transfers in this date range.</td></tr>@endforelse</tbody></table></div>{{ $transfers->links() }}</section>
@endsection

