@extends('layouts.app')
@section('title', 'Terminals & fares')
@section('content')
<div class="page-heading"><div><p class="eyebrow">SET UP YOUR CAMPUS</p><h1>The right route. A clear fare.</h1><p>Changes apply to new runs. Boarding runs retain their agreed fare and capacity.</p></div></div>
<div class="two-column"><section class="panel"><h2>Campus terminals</h2><p>Edit the sample names to match your transport points.</p>@foreach($terminals as $terminal)<form class="inline-form separated" action="{{ route('admin.terminals.save', $terminal) }}" method="post">@csrf<label>Terminal name<input name="name" value="{{ $terminal->name }}" required maxlength="80"></label><label>Status<select name="active"><option value="1" @selected($terminal->active)>Active</option><option value="0" @selected(!$terminal->active)>Inactive</option></select></label><button class="btn btn-small btn-light" type="submit">Save</button></form>@endforeach<details class="disclosure"><summary>+ Add terminal</summary><form method="post" action="{{ route('admin.terminals.save') }}" class="form-stack">@csrf<input type="hidden" name="active" value="1"><label>Terminal name<input name="name" maxlength="80" required></label><button class="btn btn-light" type="submit">Add terminal</button></form></details></section>
<section class="panel"><h2>Add or update a fare</h2><p>Choose a route and bus type. Saving replaces that combination's fare.</p><form action="{{ route('admin.fares.save') }}" method="post" class="form-stack">@csrf<div class="form-grid"><label>Origin<select name="origin_id" required>@foreach($terminals as $terminal)<option value="{{ $terminal->id }}" @selected(old('origin_id') == $terminal->id)>{{ $terminal->name }}</option>@endforeach</select></label><label>Destination<select name="destination_id" required>@foreach($terminals as $terminal)<option value="{{ $terminal->id }}" @selected(old('destination_id', $terminals->last()?->id) == $terminal->id)>{{ $terminal->name }}</option>@endforeach</select></label></div><div class="form-grid"><label>Bus type<select name="bus_type">@foreach(\App\Models\Bus::TYPES as $type)<option @selected(old('bus_type') === $type)>{{ $type }}</option>@endforeach</select></label><label>Fare (NGN)<input name="amount" inputmode="decimal" placeholder="200.00" value="{{ old('amount') }}" required></label></div><label>Status<select name="active"><option value="1">Active</option><option value="0">Inactive</option></select></label><button class="btn btn-primary" type="submit">Save fare</button></form></section></div>
<section class="panel section-gap"><h2>Fare directory</h2><div class="table-scroll"><table><thead><tr><th>Direction</th><th>Bus type</th><th>Fare per seat</th><th>Status</th></tr></thead><tbody>@forelse($fares as $fare)<tr><td>{{ $fare->origin->name }} → {{ $fare->destination->name }}</td><td>{{ $fare->bus_type }}</td><td>{{ \App\Support\Money::format($fare->amount_kobo) }}</td><td><span class="badge {{ $fare->active ? 'approved' : 'cancelled' }}">{{ $fare->active ? 'Active' : 'Inactive' }}</span></td></tr>@empty<tr><td colspan="4" class="table-empty">Add a fare to allow drivers to open runs.</td></tr>@endforelse</tbody></table></div></section>
@endsection

