@extends('layouts.app')
@section('title', 'My ticket')
@section('content')
<a class="back-link" href="{{ route('bookings') }}">← All my tickets</a>
<div class="page-heading"><div><p class="eyebrow">YOUR CAMPUS PASS</p><h1>{{ $booking->status === 'cancelled' ? 'This ticket is cancelled.' : 'Your seat is reserved.' }}</h1><p>{{ $booking->status === 'cancelled' ? 'The fare has been returned to your transport wallet.' : 'Show this booking code to your driver at the terminal.' }}</p></div></div>
<div class="two-column"><article class="ticket"><div class="ticket-header"><div class="brand"><span class="brand-mark"><x-icon name="bus" /></span>FUL<span class="brand-light">move</span></div><span class="badge {{ $booking->status }}">{{ ucfirst($booking->status) }}</span></div><div class="ticket-body"><div class="journey-stops"><div><span class="stop-dot"></span><p>FROM<strong>{{ $booking->run->origin->name }}</strong></p></div><div><span class="stop-dot filled"></span><p>TO<strong>{{ $booking->run->destination->name }}</strong></p></div></div><div class="detail-grid"><div><span>Passenger</span><strong>{{ auth()->user()->name }}</strong></div><div><span>Bus</span><strong>{{ $booking->run->bus->identifier }}</strong></div><div><span>Fare paid</span><strong>{{ \App\Support\Money::format($booking->fare_kobo) }}</strong></div><div><span>Run status</span><strong>{{ ucfirst($booking->run->status) }}</strong></div><div><span>Estimated departure</span><strong>{{ $booking->run->estimate_label }}</strong></div><div><span>Estimate updated</span><strong>{{ $booking->run->estimate_updated_at->format('d M, g:i A') }} WAT</strong></div></div></div><div class="ticket-code"><span class="eyebrow">YOUR BOOKING CODE</span><strong>{{ $booking->booking_code }}</strong><span>One seat · Booked {{ $booking->created_at->format('d M Y, g:i A') }}</span></div></article><aside>@if($booking->status === 'cancelled')<div class="panel"><h2>Find your next ride.</h2><p>This ticket is no longer valid for boarding. Your credit is back in your wallet whenever you are ready to book again.</p><a class="btn btn-primary" href="{{ route('board') }}">Find another bus <x-icon name="arrow" /></a></div>@else<div class="panel"><h2>You're all set.</h2><div class="step"><span>1</span><div><strong>Head to the terminal</strong><p>Arrive before boarding closes. Your driver may leave early.</p></div></div><div class="step"><span>2</span><div><strong>Show this ticket</strong><p>The driver will check your booking code and mark you boarded.</p></div></div></div>@endif @if($booking->can_cancel)<form class="panel cancel-panel" action="{{ route('tickets.cancel', $booking) }}" method="post" data-confirm="Cancel this ticket and return the fare to your wallet?">@csrf<h3>Plans changed?</h3><p>You can cancel before check-in while the bus is boarding.</p><button type="submit" class="btn btn-danger full">Cancel & refund ticket</button></form>@endif</aside></div>
@endsection


