@extends('layouts.app')
@section('title', 'Manage run')
@section('content')
<a class="back-link" href="{{ route('driver.index') }}">← Driver dashboard</a>
<div class="page-heading"><div><p class="eyebrow">RUN #{{ $run->id }} · {{ $run->bus->identifier }}</p><h1>{{ $run->origin->name }} → {{ $run->destination->name }}</h1><p>{{ $run->bus->type }} · {{ \App\Support\Money::format($run->fare_snapshot_kobo) }} per online seat</p></div><span class="badge {{ $run->status }}">{{ ucfirst($run->status) }}</span></div>
<div class="stats-grid"><div class="stat"><span>Total capacity</span><strong>{{ $run->capacity_snapshot }}</strong></div><div class="stat"><span>Online bookings</span><strong>{{ $run->active_bookings_count }}</strong></div><div class="stat"><span>Walk-ins</span><strong>{{ $run->walk_in_count }}</strong></div><div class="stat green-stat"><span>Seats remaining</span><strong>{{ $run->seats_left }}</strong></div></div>
@if($run->status === 'boarding')
@if($run->estimated_departure_at->isPast())<div class="notice error"><x-icon name="clock" /><span>The departure estimate has passed. Update it below or close boarding and depart.</span></div>@endif
<div class="two-column section-gap"><section class="panel"><h2>Keep students in the loop.</h2><form action="{{ route('driver.runs.update', $run) }}" method="post" class="form-stack">@csrf @method('PATCH')<label>Estimated departure (WAT)<input type="datetime-local" name="estimated_departure_at" value="{{ now()->max($run->estimated_departure_at->copy())->addMinutes(5)->format('Y-m-d\TH:i') }}" required></label><button class="btn btn-light" type="submit">Update estimate</button></form><small class="muted">Current estimate: {{ $run->estimate_label }} · Updated {{ $run->estimate_updated_at->format('g:i A') }}</small></section><section class="panel"><h2>Walk-in passengers</h2><p>Enter the total number without an online booking. Online passengers already hold their seats.</p><form action="{{ route('driver.runs.update', $run) }}" method="post" class="inline-form">@csrf @method('PATCH')<label>Total walk-ins<input type="number" name="walk_in_count" min="0" max="{{ $run->capacity_snapshot - $run->active_bookings_count }}" value="{{ $run->walk_in_count }}" required></label><button class="btn btn-light" type="submit">Save count</button></form><p class="tiny">Walk-ins reduce seats only. Cash fares are outside this app.</p></section></div>
@endif
<section class="panel section-gap"><div class="section-heading"><div><h2>Passenger list</h2><p>Match each student's name and booking code before check-in.</p></div><a class="btn btn-light btn-small" href="{{ route('driver.runs.show', $run) }}">Refresh list</a></div><div class="table-scroll"><table><thead><tr><th>Student</th><th>Booking code</th><th>Fare</th><th>Status</th><th></th></tr></thead><tbody>@forelse($run->bookings as $booking)<tr><td><strong>{{ $booking->student->name }}</strong><small>{{ $booking->student->student_identifier }}</small></td><td><code>{{ $booking->booking_code }}</code></td><td>{{ \App\Support\Money::format($booking->fare_kobo) }}</td><td><span class="badge {{ $booking->status }}">{{ ucfirst($booking->status) }}</span></td><td>@if($run->status === 'boarding' && $booking->status === 'booked')<form action="{{ route('driver.bookings.board', $booking) }}" method="post">@csrf<button class="btn btn-small btn-primary" type="submit">Mark boarded</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="table-empty">No online bookings yet. Refresh to see new passengers.</td></tr>@endforelse</tbody></table></div></section>
<div class="actions section-gap">
@if($run->status === 'boarding')
<form method="post" action="{{ route('driver.runs.status', $run) }}" data-confirm="Close boarding and depart now? New bookings and student refunds will stop.">@csrf<input type="hidden" name="status" value="departed"><button class="btn btn-primary" type="submit">Close boarding & depart <x-icon name="arrow" /></button></form>
<form method="post" action="{{ route('driver.runs.status', $run) }}" data-confirm="Cancel this run and refund every active online booking, including boarded passengers?">@csrf<input type="hidden" name="status" value="cancelled"><button class="btn btn-danger" type="submit">Cancel run & refund</button></form>
@elseif($run->status === 'departed')
<form method="post" action="{{ route('driver.runs.status', $run) }}">@csrf<input type="hidden" name="status" value="arrived"><button class="btn btn-primary" type="submit">Mark arrived at destination <x-icon name="check" /></button></form>
@endif</div>
@endsection


